const Router = require('express')
const router = new Router()
const userRouter = require('./user.router')
const adminRouter = require('./admin.router')
const teamsRouter = require('./team.router')
const ligaRouter = require('./liga.router')
const cityRouter = require('./city.router')
const advertisementRouter = require('./advertisement.router')
router.use('/user', userRouter)
router.use('/admin', adminRouter)
router.use('/teams', teamsRouter)
router.use('/ligas', ligaRouter)
router.use('/city',cityRouter)
router.use('/advertisement',advertisementRouter)
module.exports = router